package edu.missouri.fakespeares.factory;

import edu.missouri.fakespeares.pizzatypes.AbstractPizza;
import edu.missouri.fakespeares.pizzatypes.PizzaType;

public class PizzaCookingFactory
{
	/**
	 * Creates an {@code AbstractPizza} instance and instantiates it according 
	 * to the {@code pizzaType} parameter. It also sets the {@code pizzaOrderID} 
	 * of the pizza using the current {@code orderIDCounter} of the pizza. The 
	 * {@code orderIDCounter} will be incremented and assigned automatically on 
	 * every creation of pizza, to assign unique pizza order IDs.
	 * 
	 * @param pizzaType The type of pizza to initialize.
	 * @return A pizza generated by the default constructor of that type.
	 */
	public AbstractPizza createPizza(PizzaType pizzaType)
	{
		// Use the PizzaType method that creates a pizza 
		return pizzaType.createPizza();
	}
}
